runtime: python27
api_version: 1
threadsafe: true 

handlers:
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest